spring.application.name=OptimizerPC_Back


spring.datasource.url=jdbc:postgresql://dpg-d13fsnogjchc73ca1tjg-a.frankfurt-postgres.render.com:5432/optimizerpc_ajmb
spring.datasource.username=user
spring.datasource.password=K5vuFGk4KirlQPMJQJ7hzdqWw4bBwrxY
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
cloudinary.cloud_name=dozrtjcih
cloudinary.api_key=427781924792898
cloudinary.api_secret=5pE1ScbzSFkRlmQDTVGLlmyhWFY

spring.security.user.name=admin
spring.security.user.password=admin

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Europe/Madrid


springdoc.swagger-ui.path=/
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operations-sorter=method
